package:
  name: pandoc-fignos
  version: "0.20"

source:
  fn: pandoc-fignos-0.20.tar.gz
  url: https://pypi.python.org/packages/27/b6/6f7a1f34ba7c5215c87bf23ba39881ef98fc1bce52962463afb2c266eebe/pandoc-fignos-0.20.tar.gz
  md5: 84104b92d0f4818be336f4ba47fb38ba
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandoc-fignos = pandoc-fignos:main
    #
    # Would create an entry point called pandoc-fignos that calls pandoc-fignos.main()

    - pandoc-fignos = pandoc_fignos:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pandoc-xnos >=0.8.2
    - pandocfilters
    - pandoc-attributes

  run:
    - python
    - pandoc-xnos >=0.8.2
    - pandocfilters
    - pandoc-attributes

test:
  # Python imports
  # imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pandoc-fignos --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/tomduck/pandoc-fignos
  license: GNU General Public License v3 (GPLv3)
  summary: 'Figure number filter for pandoc'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
