package:
  name: pandoc-attributes
  version: "0.1.7"

source:
  fn: pandoc-attributes-0.1.7.tar.gz
  url: https://pypi.python.org/packages/c2/0a/442cc9237dc997cd88155bdcb54bf86e703e699881f4134ecb733ccd670c/pandoc-attributes-0.1.7.tar.gz
  md5: 726dcac5ddfadd877db52683d0fe4848
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandoc-attributes = pandoc-attributes:main
    #
    # Would create an entry point called pandoc-attributes that calls pandoc-attributes.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pandocfilters

  run:
    - python
    - pandocfilters

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/aaren/pandoc-attributes
  license: BSD 2-Clause
  summary: 'An Attribute class to be used with pandocfilters'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
